name: Automated Public Tests
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Setup Node and NPM
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

  test:
    if: github.repository != 'riehlegroup/adap-names'
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Setup Node and NPM
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm ci

      - name: Run tests for exercise B01
        run: npm run test:b01
        if: ${{ !cancelled() && github.event.head_commit.timestamp >= '2024-10-21T12:00:00Z' }}

      - name: Run tests for exercise B02
        run: npm run test:b02
        if: ${{ !cancelled() && github.event.head_commit.timestamp >= '2024-10-28T12:00:00Z' }}

      - name: Run tests for exercise B03
        run: npm run test:b03
        if: ${{ !cancelled() && github.event.head_commit.timestamp >= '2024-11-11T12:00:00Z' }}

      - name: Run tests for exercise B04
        run: npm run test:b04
        if: ${{ !cancelled() && github.event.head_commit.timestamp >= '2024-11-18T12:00:00Z' }}

      - name: Run tests for exercise B05
        run: npm run test:b05
        if: ${{ !cancelled() && github.event.head_commit.timestamp >= '2024-11-25T12:00:00Z' }}

      - name: Run tests for exercise B06
        run: npm run test:b06
        if: ${{ !cancelled() && github.event.head_commit.timestamp >= '2024-12-02T12:00:00Z' }}
